[project]
name = "nonebot-plugin-osubot"
version = "0.8.0"
description = "OSUbot in NoneBot2"
authors = [
    {name = "yaowan233", email = "572473053@qq.com"},
]
license = {text = "AGPL-3.0"}
dependencies = [
    "nonebot2>=2.0.0b4",
    "nonebot-adapter-onebot>=2.0.0b1",
    "pillow>=9.2.0",
    "matplotlib>=3.5.2",
    "expiringdict>=1.2.2",
    "nonebot-plugin-apscheduler>=0.1.3",
    "aiohttp>=3.8.1",
    "tortoise-orm>=0.19.2",
    "nonebot-plugin-tortoise-orm>=0.0.1a3",
]
requires-python = ">=3.8"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/yaowan233/nonebot-plugin-osubot"
Repository = "https://github.com/yaowan233/nonebot-plugin-osubot"

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
[tool]
[tool.pdm]
