[project]
name = "nonebot-plugin-osubot"
version = "0.1.0"
description = "OSUbot in NoneBot2"
authors = [
    {name = "Yaowan233", email = "572473053@qq.com"},
]
license-expression = "MIT"
dependencies = ["nonebot2>=2.0.0b3", "nonebot-adapter-onebot>=2.0.0b1"]
requires-python = ">=3.8"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/yaowan233/nonebot-plugin-osubot"
Repository = "https://github.com/yaowan233/nonebot-plugin-osubot"

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"