[project]
name = "nonebot-plugin-osubot"
version = "4.1.0"
description = "OSUbot in NoneBot2"
authors = [
    {name = "yaowan233", email = "572473053@qq.com"},
]
license = {text = "AGPL-3.0"}
dependencies = [
    "nonebot2>=2.0.0",
    "nonebot-adapter-onebot>=2.2.4",
    "pillow>=9.2.0",
    "expiringdict>=1.2.2",
    "nonebot-plugin-apscheduler>=0.2.0",
    "tortoise-orm>=0.20.0",
    "nonebot-plugin-tortoise-orm>=0.1.1",
    "rosu-pp-py==0.9.1",
    "reamber>=0.1.9",
    "nonebot-plugin-guild-patch>=0.2.2",
    "httpx>=0.23.3",
    "typing-extensions>=4.5.0",
    "matplotlib>=3.7.1",
    "nonebot-adapter-red>=0.7.2",
]
requires-python = ">=3.8"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/yaowan233/nonebot-plugin-osubot"
Repository = "https://github.com/yaowan233/nonebot-plugin-osubot"

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[tool.pdm.dev-dependencies]
test = [
    "nonebug>=0.3.5",
    "pytest-asyncio>=0.21.1",
    "fastapi>=0.103.1",
    "uvicorn>=0.23.2",
]
